CREATE TABLE IF NOT EXISTS COUNTRY (
    id VARCHAR(3),
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS COUNTRY2 (
    id VARCHAR(3),
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS COUNTRY3 (
    id VARCHAR(3),
    name VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS COUNTRY4 (
    id VARCHAR(3),
    name VARCHAR(100)
);